version: "3.8"

services:
  mariadb:
    image: mariadb:10.5.10
    container_name: jestebanrods_mariadb
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./mariadb_data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=1234567890

  wordpress:
    image: wordpress:5.7.2-php8.0-apache
    container_name: jestebanrods_wordpress
    restart: always
    depends_on:
      - mariadb
    ports:
      - 8080:80
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "VeZdF7Qd2E"
      WORDPRESS_DB_NAME: wordpress

  backup:
    image: aveltens/wordpress-backup:latest
    container_name: jestebanrods_backups
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./backups:/backups
    volumes_from:
      - wordpress
    depends_on:
      - wordpress
    environment:
      MYSQL_ENV_MYSQL_DATABASE: wordpress
      MYSQL_ENV_MYSQL_USER: wordpress
      MYSQL_ENV_MYSQL_PASSWORD: "VeZdF7Qd2E"
      MYSQL_PORT_3306_TCP_PORT: 3306
      CLEANUP_OLDER_THAN: 5
      BACKUP_TIME: "0 2 * * *"

  moodle:
    image: bitnami/moodle:3.10.3
    container_name: jestebanrods_moodle
    restart: always
    ports:
      - 8081:8080
      # - 443:8443
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_PASSWORD=VeZdF7Qd2E
      - MOODLE_PASSWORD=1234567890
      - MOODLE_USERNAME=superadmin
      - MOODLE_EMAIL=jestebanrods@gmail.com
      - MOODLE_SITE_NAME=academy
      # - BITNAMI_DEBUG=true
    volumes:
      - './moodle_data:/bitnami/moodle'
      - './moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
