version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: jestebanrods_mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234567890"
      MYSQL_DATABASE: "jestebanrods"
