version: "3.8"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:0.12.0
    network_mode: bridge
    ports:
        - '4566:4566'
    environment:
        - AWS_DEFAULT_REGION=us-east-1
        - EDGE_PORT=4566
        - SERVICES=sns
    volumes:
        - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
        - "/var/run/docker.sock:/var/run/docker.sock"

# http://localhost:4566/health
